name: Sample Workflow

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: sample-project-id
  USERNAME: sample-username
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current code using public action
        uses: actions/checkout@v2
      - name: get the list of files in our current directory and its subdirecs
        run: |
          pwd
          ls -alR

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print current files
        run: |
          pwd
          ls -aLR

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: print env variables
        run: echo $VAR1 $VAR2 $VAR3
        env:
          VAR1: Thanks
          VAR2: You
          VAR3: printprint